# -*- coding: utf-8 -*-
"""Assignment1_Part1_Regex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BfLHWlLvf-T3kKRTT2z6HC61xbeaCTCo

# Assignment 1 - Part 1: Regular Expressions and Date Extraction

**Course:** Natural Language Processing

**Total Points:** 10 points (contributes to 50% of Assignment 1)

---

## Instructions

1. Complete all the functions marked with `# YOUR CODE HERE`
2. **DO NOT** change the function names or their signatures
3. Each function must return the exact type specified
4. Test your functions by running the test cells
5. When finished:
   - Export this notebook as a Python file (.py)
   - **Name the file:** `LASTNAME_FIRSTNAME_assignment1_part1.py`
   - Example: `DUPONT_Jean_assignment1_part1.py`
   - Push to your GitHub repository
   - Send the .py file by email to: **yoroba93@gmail.com**

---

## Assignment Overview

In this assignment, you'll work with messy medical data and use regex to extract relevant information.

Each line of the `dates.txt` file corresponds to a medical note. Each note has a date that needs to be extracted, but dates are encoded in many different formats.

**Date formats you may encounter:**
- `04/20/2009; 04/20/09; 4/20/09; 4/3/09`
- `Mar-20-2009; Mar 20, 2009; March 20, 2009; Mar. 20, 2009; Mar 20 2009`
- `20 Mar 2009; 20 March 2009; 20 Mar. 2009; 20 March, 2009`
- `Mar 20th, 2009; Mar 21st, 2009; Mar 22nd, 2009`
- `Feb 2009; Sep 2009; Oct 2010`
- `6/2008; 12/2009`
- `2009; 2010`

---

## Setup
"""

import pandas as pd
import numpy as np
import re
from datetime import datetime

# Load the data
doc = []
with open('dates.txt') as file:
    for line in file:
        doc.append(line)

df = pd.Series(doc)
print(f"Loaded {len(df)} medical notes")
print("\nFirst 5 notes:")
print(df.head())

"""---

## Question 1 (1 point)

**Write a regex pattern to extract dates in the format `MM/DD/YY` or `MM/DD/YYYY`.**

Examples: `03/25/93`, `6/18/85`, `5/24/1990`, `1/25/2011`

*This function should return a list of all matched date strings.*
"""

def question_one(df):
    """
    Extract all dates in MM/DD/YY or MM/DD/YYYY format.

    Returns:
        list: List of matched date strings
    """
    # YOUR CODE HERE
    # Pattern for MM/DD/YY or MM/DD/YYYY
    # Month: 01-12 (single digit months allowed, e.g., 4/)
    # Day: 01-31 (single digit days allowed, e.g., /3/)
    # Year: 2 or 4 digits
    pattern = r'\b(0?[1-9]|1[0-2])/(0?[1-9]|[1-2][0-9]|3[0-1])/(\d{2}|\d{4})\b'  # Define your regex pattern

    results = []
    for note in df:
        matches = re.findall(pattern, note)
        # re.findall with groups returns a list of tuples, join them back for the result
        formatted_matches = ['/'.join(match) for match in matches]
        results.extend(formatted_matches)

    return results

# Test your function
q1_result = question_one(df)
print(f"Found {len(q1_result)} dates")
print(f"First 10: {q1_result[:10]}")

"""---

## Question 2 (1 point)

**Write a regex pattern to extract dates with month names.**

Examples: `Mar-20-2009`, `March 20, 2009`, `Mar 20 2009`, `Mar. 20, 2009`

*This function should return a list of all matched date strings.*
"""

def question_two():
    """
    Extract all dates with month names (e.g., Mar 20, 2009).

    Returns:
        list: List of matched date strings
    """
    # Regex to match month name, day, and year combinations
    # Handles abbreviated (Jan) and full (January) month names
    # Accounts for optional period after abbreviation (Mar.)
    # Allows for various separators: space, hyphen, comma
    month_names = r'(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)'
    day_pattern = r'(?:0?[1-9]|[12][0-9]|3[01])'
    year_pattern = r'\d{4}'
    separator = r'(?:\s+|\-|\,\s*)'

    pattern = fr'\b{month_names}\.?(?:{separator}{day_pattern})?(?:{separator}{year_pattern})?\b'

    # Adjusting for specific examples given in Q2:
    # Mar-20-2009; Mar 20, 2009; March 20, 2009; Mar. 20, 2009; Mar 20 2009
    # These all include a day, so `day_pattern` and `year_pattern` should not be optional.
    # Let's ensure the pattern is robust for these exact cases.
    pattern = fr'\b{month_names}\.?(?:\s+|\-|\,\s*){day_pattern}(?:\s+|\-|\,\s*){year_pattern}\b'

    results = []
    for note in df:
        # re.findall finds all non-overlapping matches
        matches = re.findall(pattern, note)
        results.extend(matches)

    return results

# Test your function
q2_result = question_two()
print(f"Found {len(q2_result)} dates")
print(f"First 10: {q2_result[:10]}")

"""---

## Question 3 (1 point)

**Write a regex pattern to extract dates in the format `DD Month YYYY`.**

Examples: `20 Mar 2009`, `20 March 2009`, `20 Mar. 2009`

*This function should return a list of all matched date strings.*
"""

def question_three():
    """
    Extract all dates in DD Month YYYY format.

    Returns:
        list: List of matched date strings
    """
    # Regex to match day, month name, and year
    # DD: 01-31
    # Month: Abbreviated (Mar) or Full (March), with optional period
    # YYYY: Four digits
    day_pattern = r'(?:0?[1-9]|[12][0-9]|3[01])'
    month_names = r'(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)'
    year_pattern = r'\d{4}'

    # Combine patterns with flexible separators and optional period for month
    pattern = fr'\b{day_pattern}\s+{month_names}\.?\s+{year_pattern}\b'

    results = []
    for note in df:
        matches = re.findall(pattern, note)
        results.extend(matches)

    return results

# Test your function
q3_result = question_three()
print(f"Found {len(q3_result)} dates")
print(f"First 10: {q3_result[:10]}")

"""---

## Question 4 (1 point)

**Write a function that uses regex to extract all email addresses from a given text.**

Test text is provided below.

*This function should return a list of email addresses.*
"""

def question_four(text):
    """
    Extract all email addresses from text.

    Args:
        text (str): Input text

    Returns:
        list: List of email addresses
    """
    # Regex to match common email address patterns
    # Supports alphanumeric characters, periods, underscores, and hyphens in the local part
    # Supports alphanumeric characters and hyphens in the domain, with at least two parts after the dot
    pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'

    return re.findall(pattern, text)

# Test your function
test_text = """
Contact us at support@company.com or sales@company.org.
You can also reach john.doe@email.co.uk or jane_doe123@university.edu.
Invalid emails: @invalid.com, user@, not-an-email
"""

q4_result = question_four(test_text)
print(f"Found emails: {q4_result}")

"""---

## Question 5 (1 point)

**Write a function that uses regex to clean text by:**
1. Removing all digits
2. Removing all punctuation except spaces
3. Converting to lowercase
4. Removing extra whitespace

*This function should return the cleaned string.*
"""

def question_five(text):
    """
    Clean text by removing digits, punctuation, and normalizing whitespace.

    Args:
        text (str): Input text

    Returns:
        str: Cleaned text
    """
    # Remove digits
    cleaned_text = re.sub(r'\d+', '', text)
    # Remove punctuation except spaces
    cleaned_text = re.sub(r'[^\w\s]', '', cleaned_text)
    # Convert to lowercase
    cleaned_text = cleaned_text.lower()
    # Remove extra whitespace (replace multiple spaces with a single space, and strip leading/trailing spaces)
    cleaned_text = re.sub(r'\s+', ' ', cleaned_text).strip()

    return cleaned_text

# Test your function
test_text = "Hello, World! 123 This is a TEST... with 456 numbers!!!"
q5_result = question_five(test_text)
print(f"Original: '{test_text}'")
print(f"Cleaned:  '{q5_result}'")
# Expected: 'hello world this is a test with numbers'

"""---

## Question 6 (2 points)

**Write a function that extracts and validates phone numbers.**

Valid formats:
- `XXX-XXX-XXXX`
- `(XXX) XXX-XXXX`
- `XXX.XXX.XXXX`
- `XXX XXX XXXX`

*This function should return a list of phone numbers in standardized format `XXX-XXX-XXXX`.*
"""

def question_six(text):
    """
    Extract phone numbers and return them in XXX-XXX-XXXX format.

    Args:
        text (str): Input text

    Returns:
        list: List of phone numbers in XXX-XXX-XXXX format
    """
    # Regex to capture phone numbers in various formats:
    # (XXX) XXX-XXXX, XXX-XXX-XXXX, XXX.XXX.XXXX, XXX XXX XXXX
    # It captures the three digit groups separately.
    pattern = r'\(?(\d{3})\)?[ .-]?(\d{3})[ .-]?(\d{4})'

    found_numbers = re.findall(pattern, text)
    standardized_numbers = []

    for groups in found_numbers:
        # groups will be a tuple like ('123', '456', '7890')
        # Join the captured groups with hyphens to form the standardized format
        standardized_numbers.append(f"{groups[0]}-{groups[1]}-{groups[2]}")

    return standardized_numbers

# Test your function
test_text = """
Call us at 123-456-7890 or (555) 123-4567.
You can also reach us at 888.555.1234 or 999 888 7777.
Invalid: 12-34-5678, 1234567890
"""

q6_result = question_six(test_text)
print(f"Found phones: {q6_result}")
# Expected: ['123-456-7890', '555-123-4567', '888-555-1234', '999-888-7777']

"""---

## Question 7 (3 points)

**This is the main challenge: Extract all dates from the medical notes and sort them chronologically.**

**Rules:**
- Assume all dates in `xx/xx/xx` format are `mm/dd/yy`
- Assume all 2-digit years are from the 1900s (e.g., `1/5/89` is January 5th, 1989)
- If the day is missing (e.g., `9/2009`), assume it is the 1st day of the month
- If the month is missing (e.g., `2010`), assume it is January 1st

*This function should return a pandas Series of length 500, where the values are the original indices sorted by date in ascending chronological order.*

**Example:**
```python
# If original series was:
#    0    1999
#    1    2010
#    2    1978
# Your function should return:
#    0    2    (1978 is earliest)
#    1    0    (1999 is second)
#    2    1    (2010 is latest)
```
"""

def question_seven():
    """
    Extract dates from all medical notes and return indices sorted chronologically.

    Returns:
        pd.Series: Series of length 500 with original indices sorted by date
    """
    # YOUR CODE HERE
    # Hint:
    # 1. Create regex patterns to match different date formats
    # 2. Extract dates from each note
    # 3. Parse dates into datetime objects
    # 4. Sort by date and return the indices

    return pd.Series([])  # Return the sorted indices

# Test your function
q7_result = question_seven()
print(f"Result length: {len(q7_result)}")
print(f"First 10 indices: {list(q7_result.head(10))}")
print(f"Last 10 indices: {list(q7_result.tail(10))}")

"""---

## Summary of Functions for Grading

Make sure all these functions are properly implemented before exporting:
"""

# Run this cell to verify all functions exist and return correct types
print("Checking functions...")

try:
    r1 = question_one(df)
    assert isinstance(r1, list), "question_one should return a list"
    print("✓ question_one: OK")
except Exception as e:
    print(f"✗ question_one: {e}")

try:
    r2 = question_two()
    assert isinstance(r2, list), "question_two should return a list"
    print("✓ question_two: OK")
except Exception as e:
    print(f"✗ question_two: {e}")

try:
    r3 = question_three()
    assert isinstance(r3, list), "question_three should return a list"
    print("✓ question_three: OK")
except Exception as e:
    print(f"✗ question_three: {e}")

try:
    r4 = question_four("test@email.com")
    assert isinstance(r4, list), "question_four should return a list"
    print("✓ question_four: OK")
except Exception as e:
    print(f"✗ question_four: {e}")

try:
    r5 = question_five("Hello World 123")
    assert isinstance(r5, str), "question_five should return a string"
    print("✓ question_five: OK")
except Exception as e:
    print(f"✗ question_five: {e}")

try:
    r6 = question_six("123-456-7890")
    assert isinstance(r6, list), "question_six should return a list"
    print("✓ question_six: OK")
except Exception as e:
    print(f"✗ question_six: {e}")

try:
    r7 = question_seven()
    assert isinstance(r7, pd.Series), "question_seven should return a pandas Series"
    print("✓ question_seven: OK")
except Exception as e:
    print(f"✗ question_seven: {e}")

print("\nDone! Export this notebook as .py file when all functions pass.")

"""---

## Submission Checklist

- [ ] All 7 functions are implemented
- [ ] All functions return the correct type
- [ ] Notebook exported as Python file
- [ ] File named: `LASTNAME_FIRSTNAME_assignment1_part1.py`
- [ ] Pushed to GitHub repository
- [ ] Sent to **yoroba93@gmail.com**
"""